// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react'

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'dumi-context-layout' }
  } as const
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__404" */ '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.5_@types+node@18.19.1_eslint@8.55.0_jest@29.7.0_prettier@3.1.0_r_ind2erg6c4t65dilxjypvc6y5y/node_modules/dumi/dist/client/pages/404.js'
          )
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/dumi/.dumi/tmp/dumi/theme/ContextWrapper'
          )
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */ '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.5_@types+node@18.19.1_eslint@8.55.0_jest@29.7.0_prettier@3.1.0_r_ind2erg6c4t65dilxjypvc6y5y/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          )
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/dumi/docs/index.md'
          )
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */ '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.5_@types+node@18.19.1_eslint@8.55.0_jest@29.7.0_prettier@3.1.0_r_ind2erg6c4t65dilxjypvc6y5y/node_modules/dumi/dist/client/pages/Demo/index.js'
          )
      )
    }
  }
}
