// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { getSketchJSON } from '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/dumi/.dumi/tmp/plugin-html2sketch'
// plugins types.d.ts
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  Helmet,
  HelmetProvider,
  createSearchParams,
  generatePath,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  resolvePath,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRoutes,
  useSearchParams,
  useAppData,
  useClientLoaderData,
  useRouteProps,
  useSelectedRoutes,
  useServerLoaderData,
  renderClient,
  __getRoot,
  Link,
  useRouteData,
  __useFetcher,
  withRouter
} from '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/@umijs+renderer-react@4.0.89_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
export type { History } from '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/@umijs+renderer-react@4.0.89_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager
} from '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/umi@4.0.89_@babel+core@7.23.5_@types+node@18.19.1_eslint@8.55.0_jest@29.7.0_prettier@3.1.0_re_msccwooxysvzqh4ga2yoxjs6ae/node_modules/umi/client/client/plugin.js'
export { history, createHistory } from './core/history'
export { terminal } from './core/terminal'
// react ssr
export const useServerInsertedHTML: Function = () => {}
// test
export { TestBrowser } from './testBrowser'
