// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react'
import { useOutlet, history } from 'dumi'
import { SiteContext } from '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.5_@types+node@18.19.1_eslint@8.55.0_jest@29.7.0_prettier@3.1.0_r_ind2erg6c4t65dilxjypvc6y5y/node_modules/dumi/dist/client/theme-api/context.js'
import { demos, components } from '../meta'
import { locales } from '../locales/config'

const entryExports = {}

export default function DumiContextWrapper() {
  const outlet = useOutlet()
  const [loading, setLoading] = useState(false)
  const prev = useRef(history.location.pathname)

  useEffect(() => {
    return history.listen(next => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0)
      }
    })
  }, [])

  return (
    <SiteContext.Provider
      value={{
        pkg: {
          name: 'pnpm-changesets-template',
          description: '一个pnpm+changesets的模板',
          version: '1.0.0',
          license: 'ISC',
          author: ''
        },
        historyType: 'browser',
        entryExports,
        demos,
        components,
        locales,
        loading,
        setLoading,
        hostname: undefined,
        themeConfig: {
          footer:
            'Copyright © 2023 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
          prefersColor: { default: 'light', switch: true },
          nprogress: true,
          lastUpdated: true
        },
        _2_level_nav_available: true
      }}>
      {outlet}
    </SiteContext.Provider>
  )
}
