// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/wuchanglong/Documents/workspace/study/pnpm-changesets-template/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.5_@types+node@18.19.1_eslint@8.55.0_jest@29.7.0_prettier@3.1.0_r_ind2erg6c4t65dilxjypvc6y5y/node_modules/dumi/theme-default/slots/LangSwitch/index.js'
